### ISSUE TITLE
ImportMoves is broken after upgrading to lastest Git WithKnown version

### ISSUE THREAD

**Issue by srcr** [danito/KnownImportMoves#4] opened 2016-04-20 10:09 UTC
php logging throws the following :

`"NOTICE: PHP message: PHP Catchable fatal error:  Argument 1 passed to IdnoPlugins\Importmoves\Main::construct_activity_group_array() must be of the type array, null g                                     iven, called in IdnoPlugins/Importmoves/templates/default/entity/Moves/edit.tpl.php on line 21                                      and defined in IdnoPlugins/Importmoves/Main.php on line 122"`

http://xxx/moves/edit web pages gives me HTTP 500

**Comment by danito** [comment] 2016-04-24 09:20
I can't reproduce it. Do you have the latest version of Moves? see #3

**Comment by srcr** [comment] 2016-04-24 19:56
Hi Daniel,

Yeah, I clone both Known and Moves directly from github move it to the correct locations and run it as is. I did a reinstall still same issue though... :(

**Comment by danito** [comment] 2016-04-25 11:13
ok, probably your moves token has expired and it doesn't get any data from the Moves API. 
I messed the token thing a bit up. Do you get any error when trying to re-enble the Moves plugin?

**Comment by srcr** [comment] 2016-04-25 15:30
Hi Daniel,

Yes when I go to https://srcr.nl/account/importmoves/ i get the following: 

'Oh no! Known experienced a problem!

Known experienced a problem with this page and couldn't continue. The technical details are as follows:

Fatal Error: public/IdnoPlugins/Importmoves/Main.php:83 - "Cannot use object of type IdnoPlugins\Importmoves\Main as array", on page srcr.nl/account/importmoves/
If you continue to have problems, open source users have a number of resources available '

**Comment by danito** [comment] 2016-04-26 15:44
should be fixed with latest commit. Can you update and reconnect your account to the Moves app and try again?
I'll find some time to fix feature request #5

**Comment by srcr** [comment] 2016-05-02 13:56
Works like a charm again, thanks for the fix.

**Closed as completed** 2018-05-17 09:26 UTC
